
version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: yys
      POSTGRES_PASSWORD: yys_pass
      POSTGRES_DB: yys_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    volumes:
      - ./backend/data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
volumes:
  pgdata:
